### PR TITLE
Fixing the ending paragraph tag

### PR DESCRIPTION
**Pull request by mxrch**
I think it's urgent

### CODE REVIEW

**Comment by OlivierLaflamme** [comment]
Thank you for your submission of material on a potential vulnerability. We are reviewing your report to determine its validity, and we will follow up regarding our analysis.

By submitting a vulnerability report to Olivier Laflamme, its subsidiaries and its affiliates, a perpetual, irrevocable, no charge license to all intellectual property rights licensable by you in or related to the use of this material. Also, it is important that you notify us if any of this material is not your own work or is covered by the intellectual property rights of others. Not notifying us means that you've represented that no third party intellectual property rights are involved.

**Comment by OlivierLaflamme** [comment]
Thank you @mxrch im broke so no bounty lmao.

**Comment by mxrch** [comment]
Ahh I was going to ask a minimum $1000 bounty, shit.. at least can I be in the Hall of Fame ?

**Comment by OlivierLaflamme** [comment]
A certificate of appreciation is all I can do KUDOS to you!

<a href="https://imgflip.com/i/4bv0ni"></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Pull request merged**
